Add vps release
cloudfoundry-community/bosh-softlayer-baremetal-server-release pull request #24
Opened 2016-11-30 09:08 UTC by zhanggbj

Hi dr.max @maximilien,

This PR only contains vps release code(should be small) but it is based on PR #23 (commit c993bad), so please help to merge it firstly. Thank you.

2016-11-30 21:48 UTC, maximilien requested changes
Please address comments. Also, since I merged previous PR if you resubmit this the change set will be smaller since the BMS code is removed already

2016-11-30 21:48 UTC, maximilien commented on packages/vps/packaging
> +mkdir ../src && cp -a * ../src/ && mv ../src ./src
how do you know you are in correct directory? Seems to me `mkdir ../src ...` is a bit dangerous? Is there a way to guarantee we are in correct start directory?

Look at the [Zookeeper release](https://github.com/cppforlife/zookeeper-release) [`packaging`](zookeeper-release/packages/java/packaging) scripts as examples... but other releases should have that too.

2016-11-30 21:48 UTC, maximilien commented on packages/vps/spec
> +- "**/*"
similar comment here. I think you can be more specific and only copy `golang_1.7` files

2016-12-01 07:27 UTC, zhanggbj commented on packages/vps/packaging
> +mkdir ../src && cp -a * ../src/ && mv ../src ./src
Sure, will make it more specific in next patch.

2016-12-01 07:28 UTC, zhanggbj commented on packages/vps/spec
> +- "**/*"
yes, will update in next patch. Thanks.

2016-12-01 09:42 UTC, zhanggbj commented
Comments Addressed. Please help to take another review. Thank you.

2016-12-02 22:14 UTC, maximilien approved these changes
Looks great. Merging. Best 👍

2016-12-02 22:14 UTC, merged