Add vps ci
cloudfoundry-community/bosh-softlayer-baremetal-server-release pull request #25
Opened 2016-11-30 09:25 UTC by zhanggbj

Hi dr.max @maximilien,

This PR only contains vps pipeline code(should be small) but it is based on PR #24 (commit 38a7f76), so please help to merge that one firstly. Thank you.

2016-11-30 22:06 UTC, maximilien requested changes
Please address comments and also resubmit the PR since with PR #23 merged, this PR will be smaller. Thx

2016-11-30 22:06 UTC, maximilien commented on config/dev.yml
> +latest_release_filename: "/Users/zhanggong/zhgworkspace/bosh-softlayer-baremetal-server-release/dev_releases/vps/vps-0+dev.1.yml"
Why is this hardcoded directly? Why not use some variable so when moved to prod life is easy, just changed env var value?

2016-11-30 22:06 UTC, maximilien commented on packages/vps/spec
> +- "**/*"
Let's make sure to only copy files we need instead of `**/*` prefix `golang_1.7`

2016-12-01 09:43 UTC, zhanggbj commented on config/dev.yml
> +latest_release_filename: "/Users/zhanggong/zhgworkspace/bosh-softlayer-baremetal-server-release/dev_releases/vps/vps-0+dev.1.yml"
Sorry, this line is not necessary, will remove it.

2016-12-01 09:43 UTC, zhanggbj commented on packages/vps/spec
> +- "**/*"
Updated in PR #24 .

2016-12-02 22:22 UTC, maximilien commented on ci/tasks/build-vps-candidate.sh
> +  mkdir -p blobs/golang_1.7/
We should always create params for dependencies since they are bound to change. For instance from Golang 1.7.x to 1.8 etc.

2016-12-02 22:24 UTC, maximilien approved these changes
Minor comment. Please address when adding BMS for v4

2016-12-02 22:24 UTC, merged