Add vps docs
cloudfoundry-community/bosh-softlayer-baremetal-server-release pull request #27
Opened 2016-11-30 10:24 UTC by zhanggbj

Hi dr.max @maximilien ,

This PR is for README.md and a manifest example under docs/vps-init-example.yml. It should be a small one and please help to review it after PR #25. Thank you.

The PR dependency is as below. Just FYI.

PR #18 <- PR #23 <- PR #24 <- PR #25 <- PR #26 

/cc @mattcui @jianqiu

2016-11-30 22:19 UTC, maximilien requested changes
Address and resubmit

2016-11-30 22:19 UTC, maximilien commented on ci/pipeline-vps.yml
> +resources:
If this is the docs PR, why does it include pipeline stuff?

Perhaps you need to resubmit with correct commit?

2016-11-30 22:19 UTC, maximilien commented on README.md
> -# bosh-softlayer-baremetal-server-release
where is the content for the README? Seems like it's an empty file?

2016-12-01 09:46 UTC, zhanggbj commented on README.md
> -# bosh-softlayer-baremetal-server-release
Changed this to a link to `src/github.com/cloudfoundry-community/vps/README.md`, please find it here.

2016-12-01 09:49 UTC, zhanggbj commented on ci/pipeline-vps.yml
> +resources:
Seems this is caused by PR dependency, it is supposed to be only 2 files in commit 	[310fb54](https://github.com/cloudfoundry-community/bosh-softlayer-baremetal-server-release/pull/27/commits/310fb54ee58e269bc10eb6c898fa8cfc241674b8).

2016-12-02 10:20 UTC, zhanggbj commented
Comments Addressed. Thank you.

2016-12-02 22:57 UTC, maximilien commented on README.md
> +Except this release,  following releases are also required.
Change this line to:

`The following releases are dependencies.`

2016-12-02 23:05 UTC, maximilien requested changes
Please address all comments and also rebase since you can then remove the pipeline files and resubmit. Thanks.

2016-12-02 23:05 UTC, maximilien commented on README.md
> +SoftLayer light stemcell is needed for deployment and can be found in [bosh.io](http://bosh.io/)
Put full link of the light stemcell since you can link to `latest`

2016-12-02 23:05 UTC, maximilien commented on README.md
> +You can use bosh-init from BOSH community to bootstrap a pool server on SoftLayer.
This will soon change to `bosh create-env ...`

2016-12-02 23:05 UTC, maximilien commented on README.md
> +You can find a deployment manifest example under docs named `vps-init-example.yml` which can deploy a virtual guest pooling server and please replace release, stemcell, resource and credential inform
add link to sample manifest not just name since now reader has to search for it

2016-12-02 23:05 UTC, maximilien commented on README.md
> +    databases: &20585760
use a named anchor instead of the number

2016-12-02 23:05 UTC, maximilien commented on README.md
> +```
Show example bosh output when deploying

2016-12-02 23:05 UTC, maximilien commented on README.md
> +- After deployment completes, you can login the environment and take a check. Run `monit summary`, normally if everything works well you can get an output as below.
`monit summary` assumes user ssh into VM. Why not show them the output from bosh CLI and the monit as extra if they login to VM

2016-12-02 23:05 UTC, maximilien commented on README.md
> +- To fully enable virtual guest pooling on SoftLayer, except deploying a pool server, you also need to make director to connect to it and enable pooling feature. Please refer to guide on [bosh-softla
Maybe this should be put early as a *WARNING* ?

2016-12-02 23:05 UTC, maximilien commented on ci/pipeline-vps.yml
> +resources:
Why is this file in this PR? OK.. I guess make sure it's removed when resubmitting this since I merged previous PR

2016-12-02 23:05 UTC, maximilien commented
Also, resolved the conflicts, I imagine these exist now due to the fact I merged previous PR

2016-12-06 08:01 UTC, zhanggbj commented
All comments addressed and re-submitted in PR #36. So I'll close this PR. Thank  you.

2016-12-06 08:01 UTC, closed without merging