Addressed PR #27 comments
cloudfoundry-community/bosh-softlayer-baremetal-server-release pull request #37
Opened 2016-12-06 08:11 UTC by zhanggbj

Hi dr.max @maximilien ,

Addressed all comments and re-submitted docs review here as the original one got a little messy. Thanks for your review.

2016-12-06 19:23 UTC, maximilien commented on README.md
> +> In bosh CLI v2, bosh-init is deprecated and use `bosh create-env` instead.
mention also that this doc will be updated.

2016-12-06 19:24 UTC, maximilien commented on README.md
> +>  Please make sure the machine installed bosh-init can access SoftLayer private network and you can enable SoftLayer VPN if it is outside of SoftLayer data center. This is because it need to communi
change "This is because it need" to "This is because it needs"

2016-12-06 19:29 UTC, maximilien requested changes
Grace, this is much improved. Made a few line comments and few required comments. Please try to address all and resubmit and I will merge. Thx.

2016-12-06 19:29 UTC, maximilien commented on README.md
> +
any way to add an example of the command that user would typically use. That should make their life a bit easier by cut and pasting?

2016-12-06 19:29 UTC, maximilien commented on README.md
> +```
I would also put a comment on any line where the user should change some value. Thx

2016-12-06 19:29 UTC, maximilien commented on README.md
> +bosh-init deploy <your-manifest.yml>
Use `$ bosh-init deploy <your-manifest.yml>` to make clear that this is a command a the prompt ($)

2016-12-07 03:00 UTC, zhanggbj commented
Hi dr.max @maximilien ,

All comments addressed. Thank you.

2016-12-07 23:24 UTC, maximilien approved these changes
Looks good. Merging.

Let's make sure to keep this up to date as things change, especially when BMS is added.

2016-12-07 23:24 UTC, merged